name = "OMOPCDMCohortMetrics"
uuid = "a0e55441-2516-4cdc-8f8e-432d4298e5c4"
authors = ["TheCedarPrince <jacobszelko@gmail.com> and contributors"]
version = "0.0.1"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
OMOPCDMCohortCreator = "f525a15e-a73f-4eef-870f-f901257eae22"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
